name: Publish Docker Image

on:
  push:
    branches:
      - main  # main 브랜치에 push할 때 실행

jobs:
  push_to_registry:
    name: Push Docker Image to GitHub Packages
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.USER_TOKEN }}" | docker login ghcr.io -u happy-yeachan --password-stdin

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build & Push Docker Image
      run: docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/happy-yeachan/django-app:latest --push .
